VV_coherence:
  long_name: "VV coherence"
  units: "1"
  description: "Interferometric coherence between two SAR acquisitions"
  coverage_content_type: "physicalMeasurement"

VV_gamma_nought:
  long_name: "VV gamma nought backscatter"
  units: "dB"
  description: "Flattened gamma nought backscatter in VV polarization"
  coverage_content_type: "physicalMeasurement"

VH_gamma_nought:
  long_name: "VH gamma nought backscatter"
  units: "dB"
  description: "Flattened gamma nought backscatter in VH polarization"
  coverage_content_type: "physicalMeasurement"

VV_sigma_nought:
  long_name: "VV sigma nought backscatter"
  units: "dB"
  description: "Sigma nought backscatter in VV polarization"
  coverage_content_type: "physicalMeasurement"

VH_sigma_nought:
  long_name: "VH sigma nought backscatter"
  units: "dB"
  description: "Sigma nought backscatter in VH polarization"
  coverage_content_type: "physicalMeasurement"

x:
  standard_name: "projection_x_coordinate"
  long_name: "x coordinate of projection"
  units: "m"
  axis: "X"
  coverage_content_type: "coordinate"

y:
  standard_name: "projection_y_coordinate"
  long_name: "y coordinate of projection"
  units: "m"
  axis: "Y"
  coverage_content_type: "coordinate"