VV_coherence:
  units: "1"
  long_name: "Interferometric coherence between two SAR acquisitions"
  coverage_content_type: "physicalMeasurement"
  coordinates: "lat lon"

VV_gamma_nought:
  units: "dB" # TODO: Check units for all data variables
  long_name: "Flattened gamma nought backscatter in VV polarization"
  coverage_content_type: "physicalMeasurement"
  coordinates: "lat lon"

VH_gamma_nought:
  units: "dB"
  long_name: "Flattened gamma nought backscatter in VH polarization"
  coverage_content_type: "physicalMeasurement"
  coordinates: "lat lon"

VV_sigma_nought:
  units: "dB"
  long_name: "Sigma nought backscatter in VV polarization"
  coverage_content_type: "physicalMeasurement"
  coordinates: "lat lon"

VH_sigma_nought:
  units: "dB"
  long_name: "Sigma nought backscatter in VH polarization"
  coverage_content_type: "physicalMeasurement"
  coordinates: "lat lon"

x:
  standard_name: "projection_x_coordinate"
  long_name: "x coordinate of projection"
  units: "m"
  coverage_content_type: "coordinate"

y:
  standard_name: "projection_y_coordinate"
  long_name: "y coordinate of projection"
  units: "m"
  coverage_content_type: "coordinate"

lat:
  standard_name: latitude
  long_name: latitude
  coverage_content_type: coordinate
  units: degrees_north

lon:
  standard_name: longitude
  long_name: longitude
  coverage_content_type: coordinate
  units: degrees_east